const config = {
  routes: {
    home: "/",
    products: "/products/:slug",
    productDetail: "/productDetail",
    notfound: "*",
    register: "/register",
    login: "/login",
    account: "/account",
    policySection: "/policySection",
    news: "/news",
    verify: "/verify",
    preOrderVerify: "/preorder/verify",
    resetPassword: "/reset-password",
    forgotPassword: "/forgot-password",
    cart: "/cart",
    checkout: "/checkouts",
    admin: "/admin",
    orderSuccess: "/order-success/:orderId",
    orderPayment: "/order/payment/:orderId",
    verifyEmail: "/verify-email",
  },
  accountRoutes: {
    loyalty: "/account",
    info: "/account/info/p/:username",
    orders: "/account/orders",
    wishlist: "/account/wishlist",
    addresses: "/account/addresses",
    coupons: "/account/coupons",
  },
  blogsRoutes: {
    setupDecor: "/blogs/setup-decor/",
    technology: "/blogs/technology/",
    setupDecorBlogDetail: "/blogs/setup-decor/:slug",
    technologyBlogDetail: "/blogs/technology/:slug",
  },
  seeMoreRoutes: {
    introduce: "/seeMore/introduce",
    affiliate: "/seeMore/affiliate",
    recruitment: "/recruitment",
    parTimeJobs: "/parTimeJobs",
    collections: "/collections/:slug",
    collectionsPage: "/collections",
  },
  jobDetailRoutes: {
    affiliateOperation: "/affiliateOperation",
    contentCreator: "/contentCreator",
    graphicDesigner: "/graphicDesigner",
    marketingExecutive: "/marketingExecutive",
    partTimeCustomerService: "/partTimeCustomerService",
    customerService: "/customerService",
    marketingExecutiveIntern: "/marketingExecutiveIntern",
  },
  policyRoutes: {
    loyaltyProgram: "/loyaltyProgram",
    preOrderPolicy: "/preOrderPolicy",
    returnPolicy: "/returnPolicy",
  },
  newPost: {
    EYESmartcase: "news/EYESmartcase",
    kingrowK1: "news/kingrowK1",
    smartEInkTablet: "news/smartEInkTablet",
    narwalRobot: "news/narwalRobot",
    rainShoeCover: "news/rainShoeCover",
    diceGlowFeature: "news/diceGlowFeature",
    leatherCareTips: "news/leatherCareTips",
  },
  adminRoutes: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    products: "/admin/products",
    orders: "/admin/orders",
    vouchers: "/admin/vouchers",
    payments: "/admin/payments",
    reviews: "/admin/reviews",
    analytics: "/admin/analytics",
    login: "/admin/login",
  },
};

export default config;
